openapi: 3.0.3
info:
  title: API ZF[pro]Parts Offers
  version: 1.0.0
  description: 'Specification for all endpoints related to [pro]Parts Offers API'
servers:
  - url: https://glue-backend.marketplace.mmm.azure.zf.com
    description: Staging environment
  - url: https://api.pro-parts.com/retailer/v1
    description: Production environment
paths:
  /offer:
    put:
      description: Creates or updates a single product offer.
      parameters:
        - name: client_id
          in: header
          description: The Client-ID of the Application.
          required: true
          schema:
            type: string
        - name: client_secret
          in: header
          description: The Client-Secret of Application.
          required: true
          schema:
            type: string
        - name: x-correlation-id
          in: header
          description: Use the above header to optionally pass a tracking information
            to this API, for end-to-end traceability of the operation/transaction. If
            passed, the x-correlation-id will be returned to the consumer in the API
            response.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/type'
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_1'
        '400':
          description: Bad Request
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '403':
          description: Forbidden
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '405':
          description: Method Not Allowed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '406':
          description: Not Acceptable
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '412':
          description: Precondition Failed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '415':
          description: Unsupported Media Type
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '502':
          description: Bad Gateway
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Time-out
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-codegen-request-body-name: generated
      summary: /offer
      operationId: put_offer
  /offers:
    put:
      description: Creates or updates one or more product offers.
      parameters:
        - name: client_id
          in: header
          description: The Client-ID of the Application.
          required: true
          schema:
            type: string
        - name: client_secret
          in: header
          description: The Client-Secret of Application.
          required: true
          schema:
            type: string
        - name: x-correlation-id
          in: header
          description: Use the above header to optionally pass a tracking information
            to this API, for end-to-end traceability of the operation/transaction. If
            passed, the x-correlation-id will be returned to the consumer in the API
            response.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/type_3'
        required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_4'
        '207':
          description: Multi Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_18'
        '400':
          description: Bad Request
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '403':
          description: Forbidden
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '405':
          description: Method Not Allowed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '406':
          description: Not Acceptable
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '412':
          description: Precondition Failed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '415':
          description: Unsupported Media Type
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '502':
          description: Bad Gateway
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Time-out
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-codegen-request-body-name: generated
      summary: /offers
      operationId: put_offers
    get:
      description: Retrieves product offer collection.
      parameters:
        - name: filter[proPartsOffers.productOfferReference]
          in: query
          description: The offer reference to filter on.
          schema:
            type: string
        - name: filter[proPartsOffers.merchantSku]
          in: query
          description: The merchant sku to filter on.
          schema:
            type: string
        - name: filter[proPartsOffers.brand]
          in: query
          description: The brand to filter on.
          schema:
            type: string
        - name: filter[proPartsOffers.partNumber]
          in: query
          description: The part number to filter on.
          schema:
            type: string
        - name: filter[proPartsOffers.isActive]
          in: query
          description: Boolean flag determining if only active orders are needed.
          schema:
            type: boolean
        - name: page[offset]
          in: query
          description: The results page offset.
          schema:
            type: integer
        - name: page[limit]
          in: query
          description: The results page limit.
          schema:
            type: integer
        - name: client_id
          in: header
          description: The Client-ID of the Application.
          required: true
          schema:
            type: string
        - name: client_secret
          in: header
          description: The Client-Secret of Application.
          required: true
          schema:
            type: string
        - name: x-correlation-id
          in: header
          description: Use the above header to optionally pass a tracking information
            to this API, for end-to-end traceability of the operation/transaction. If
            passed, the x-correlation-id will be returned to the consumer in the API
            response.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_2'
        '400':
          description: Bad Request
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '403':
          description: Forbidden
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '405':
          description: Method Not Allowed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '406':
          description: Not Acceptable
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '412':
          description: Precondition Failed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '415':
          description: Unsupported Media Type
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '502':
          description: Bad Gateway
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Time-out
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      summary: /offers
      operationId: get_offers
  /offers/{productOfferReference}:
    get:
      description: Retrieves a single product offer
      parameters:
        - name: productOfferReference
          in: path
          description: The offer reference
          required: true
          schema:
            type: string
        - name: client_id
          in: header
          description: The Client-ID of the Application.
          required: true
          schema:
            type: string
        - name: client_secret
          in: header
          description: The Client-Secret of Application.
          required: true
          schema:
            type: string
        - name: x-correlation-id
          in: header
          description: Use the above header to optionally pass a tracking information
            to this API, for end-to-end traceability of the operation/transaction. If
            passed, the x-correlation-id will be returned to the consumer in the API
            response.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/type_5'
        '400':
          description: Bad Request
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '403':
          description: Forbidden
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '405':
          description: Method Not Allowed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '406':
          description: Not Acceptable
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '412':
          description: Precondition Failed
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '415':
          description: Unsupported Media Type
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '502':
          description: Bad Gateway
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Time-out
          headers:
            x-correlation-id:
              description: Specify the transaction identifier received from the request
                or added by the API otherwise
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      summary: /offers/{productOfferReference}
      operationId: get_offers_productOfferReference
components:
  schemas:
    type:
      type: object
      properties:
        merchantSku:
          type: string
          example: MER000002
        brand:
          type: string
          example: BOSCH
        partNumber:
          type: string
          example: 0 261 500 109
        quantity:
          type: string
          example: '50'
        isNeverOutOfStock:
          type: boolean
          example: false
        isActive:
          type: boolean
          example: true
        netPrice:
          type: string
          example: '1000.00'
        validFrom:
          type: object
          example: 2020-03-15 00:00:00
        validTo:
          type: object
          example: 2021-03-15 00:00:00
      example:
        merchantSku: MER000002
        brand: BOSCH
        partNumber: 0 261 500 109
        quantity: '50'
        isNeverOutOfStock: false
        isActive: true
        netPrice: '1000.00'
        validFrom: 2020-03-15 00:00:00
        validTo: 2021-03-15 00:00:00
    type_1:
      required:
        - productOfferReference
      type: object
      properties:
        productOfferReference:
          type: string
          example: offer_MER000002-bosch__0-261-500-109
        merchantSku:
          type: string
          example: MER000002
        brand:
          type: string
          example: BOSCH
        partNumber:
          type: string
          example: 0 261 500 109
        quantity:
          type: string
          example: '50'
        isNeverOutOfStock:
          type: boolean
          example: false
        isActive:
          type: boolean
          example: true
        netPrice:
          type: string
          example: '599.00'
        validFrom:
          type: object
          example: 2020-03-15 00:00:00
        validTo:
          type: object
          example: 2021-03-15 00:00:00
      example:
        productOfferReference: offer_MER000002-bosch__0-261-500-109
        merchantSku: MER000002
        brand: BOSCH
        partNumber: 0 261 500 109
        quantity: '50'
        isNeverOutOfStock: false
        isActive: true
        netPrice: '1000.00'
    errorResponse:
      required:
        - error
      type: object
      properties:
        error:
          required:
            - code
            - message
            - reason
          type: object
          properties:
            code:
              type: string
            reason:
              type: string
            message:
              type: string
      description: This is generic common error handling
    type_2:
      type: array
      example:
        - productOfferReference: offer_MER000002-bosch__0-261-500-109
          merchantSku: MER000002
          brand: BOSCH
          partNumber: 0 261 500 109
          quantity: '50'
          isNeverOutOfStock: false
          isActive: true
          netPrice: '1000.00'
        - productOfferReference: offer_MER000002-bosch__0-280-157-501
          merchantSku: MER000002
          brand: BOSCH
          partNumber: 0 280 157 501
          quantity: '50'
          isNeverOutOfStock: false
          isActive: true
          netPrice: '1000.00'
        - productOfferReference: offer_MER000002-bosch__0-280-156-096
          merchantSku: MER000002
          brand: BOSCH
          partNumber: 0 280 156 096
          quantity: '50'
          isNeverOutOfStock: false
          isActive: true
          netPrice: '1000.00'
          validFrom: 2020-03-15 00:00:00
          validTo: 2021-03-15 00:00:00
      items:
        $ref: '#/components/schemas/type_5'
    type_3:
      required:
        - data
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/type'
      example:
        data:
          - merchantSku: MER000002
            brand: BOSCH
            partNumber: 0 261 500 109
            quantity: '50'
            isNeverOutOfStock: false
            isActive: true
            netPrice: '1000.00'
            validFrom: 2020-03-15 00:00:00
            validTo: 2021-03-15 00:00:00
          - merchantSku: MER000002
            brand: BOSCH
            partNumber: 0 280 157 501
            quantity: '50'
            isNeverOutOfStock: false
            isActive: true
            netPrice: '715.99'
    type_4:
      type: array
      example:
        - productOfferReference: offer_MER000002-bosch__0-261-500-109
          merchantSku: MER000002
          brand: BOSCH
          partNumber: 0 261 500 109
          quantity: '50'
          isNeverOutOfStock: false
          isActive: true
          netPrice: '1000.00'
        - productOfferReference: offer_MER000002-bosch__0-280-157-501
          merchantSku: MER000002
          brand: BOSCH
          partNumber: 0 280 157 501
          quantity: '50'
          isNeverOutOfStock: false
          isActive: true
          netPrice: '1000.00'
      items:
        $ref: '#/components/schemas/type_1'
    type_5:
      type: object
      properties:
        productOfferReference:
          type: string
          example: offer_MER000002-bosch__0-280-156-096
        merchantSku:
          type: string
          example: MER000002
        brand:
          type: string
          example: BOSCH
        partNumber:
          type: string
          example: 0 280 156 096
        quantity:
          type: string
          example: '50'
        isNeverOutOfStock:
          type: boolean
          example: false
        isActive:
          type: boolean
          example: true
        netPrice:
          type: string
          example: '1000.00'
        validFrom:
          type: object
          example: 2020-03-15 00:00:00
        validTo:
          type: object
          example: 2021-03-15 00:00:00
      example:
        productOfferReference: offer_MER000002-bosch__0-280-156-096
        merchantSku: MER000002
        brand: BOSCH
        partNumber: 0 280 156 096
        quantity: '50'
        isNeverOutOfStock: false
        isActive: true
        netPrice: '1000.00'
        validFrom: 2020-03-15 00:00:00
        validTo: 2021-03-15 00:00:00
    type_6:
      type: array
      example:
        - merchantOrderReference: BR--425--MER000015
          paymentMethod: Credit Card
          customer:
            customerReference: BR--425
            fullName: Mr Max Mustermann
            email: max@mustermann.com
            cnpj: 12.345.678/0001-23
            ie: 123.456.789.012
            companyName: Caterham Performance
          totals:
            subtotal: '299.95'
            orderExpense: '0.00'
            grand: '249.95'
            canceled: '0.00'
            refundable: '249.95'
            commission: '24.99'
            discount: '50.00'
          itemStates:
            - new
          itemCount: 5
          shipments:
            - shipmentReference: '50'
              name: Standard
              carrierName: Entrega
          updatedAt: 2024-04-01 23:59:59
          createdAt: 2024-04-01 23:59:59
      items:
        $ref: '#/components/schemas/type_9'
    type_7:
      required:
        - billingAddress
        - createdAt
        - customer
        - itemCount
        - itemStates
        - items
        - merchantOrderReference
        - paymentMethod
        - settlementDate
        - shipments
        - totals
        - updatedAt
      type: object
      properties:
        merchantOrderReference:
          type: string
          description: Unique identifier of a merchant order
          example: BR--425--MER000015
        paymentMethod:
          type: string
          description: Textual representation of the payment method
          example: Credit Card
          enum:
            - Credit Card
            - Pix
        settlementDate:
          type: string
          description: Describes the target date when order can be paid out
          example: 2024-05-15 23:59:59
        billingAddress:
          $ref: '#/components/schemas/type_10'
        customer:
          $ref: '#/components/schemas/type_11'
        totals:
          $ref: '#/components/schemas/type_12'
        itemStates:
          type: array
          description: Aggregated order item states
          example:
            - new
            - canceled
            - waiting for documents
          items:
            type: string
            description: State which belongs to at least one order item
            example: new
        itemCount:
          type: integer
          description: Count of unique order items
        items:
          type: array
          description: Order item collection of a merchant order
          items:
            $ref: '#/components/schemas/type_13'
        shipments:
          type: array
          description: An order contains at least one shipment group
          items:
            $ref: '#/components/schemas/type_14'
        updatedAt:
          type: string
          description: Order update date and time in UTC
          example: 2024-04-01 23:59:59
        createdAt:
          type: string
          description: Order creation date and time in UTC
          example: 2024-04-01 23:59:59
      example:
        merchantOrderReference: BR--425--MER000015
        paymentMethod: Credit Card
        settlementDate: 2024-05-15 23:59:59
        creditCardInstallmentsCount: 1
        billingAddress:
          salutation: Mr
          firstName: Max
          lastName: Musterman
          company: Acme Inc.
          address1: Main St.
          address2: '101'
          address3: Central
          zipCode: '12345'
          city: Springfield
          country: Scotland
          phone: 123-456-789
        customer:
          customerReference: BR--425
          fullName: Mr Max Mustermann
          email: max@mustermann.com
          cnpj: 12.345.678/0001-23
          ie: 123.456.789.012
          companyName: Caterham Performance
        totals:
          subtotal: '1775.84'
          orderExpense: '0.00'
          grand: '1598.26'
          canceled: '0.00'
          refundable: '1598.26'
          commission: '159.83'
          discount: '177.58'
        itemStates:
          - new
        itemCount: 1
        items:
          - merchantOrderItemReference: 715fba0fdef4f68b6146524b44e8fac2
            state: new
            product:
              sku: continental__7pk1525rnh
              name: CORREIA DE ACESSÓRIOS POLY V 1525MM CONTINENTAL - 7PK1525RNH
              brand: CONTINENTAL
              partNumber: 7PK1525RNH
            quantity: 16
            totals:
              unitPrice: '110.99'
              sumPrice: '1775.84'
              sumPriceToPay: '1598.26'
              discountTotal: '177.58'
            notaFiscal: ''
            trackingLink: ''
        shipments:
          - shipmentReference: '50'
            name: Standard
            carrierName: Entrega
            merchantOrderItemReferences:
              - 715fba0fdef4f68b6146524b44e8fac2
            address:
              salutation: Mr
              firstName: Max
              lastName: Musterman
              company: Acme Inc.
              address1: Main St.
              address2: '101'
              address3: Central
              zipCode: '12345'
              city: Springfield
              country: Scotland
              phone: 123-456-789
        updatedAt: 2024-04-01 23:59:59
        createdAt: 2024-04-01 23:59:59
    type_8:
      required:
        - data
      type: object
      properties:
        data:
          required:
            - merchantOrderItemReferences
          type: object
          properties:
            merchantOrderItemReferences:
              type: array
              description: List of unique identifiers of order items
              example:
                - 715fba0fdef4f68b6146524b44e8fac2
                - ff33f8f4f90f8efe400abeab49a76788
              items:
                type: string
                description: Unique identifier for order item
                example: 715fba0fdef4f68b6146524b44e8fac2
    type_9:
      required:
        - createdAt
        - customer
        - itemCount
        - itemStates
        - merchantOrderReference
        - paymentMethod
        - shipments
        - totals
        - updatedAt
      type: object
      properties:
        merchantOrderReference:
          type: string
          description: Unique identifier of a merchant order
          example: BR--425--MER000015
        paymentMethod:
          type: string
          description: Textual representation of the payment method
          example: Credit Card
          enum:
            - Credit Card
            - Pix
        customer:
          $ref: '#/components/schemas/type_11'
        totals:
          $ref: '#/components/schemas/type_12'
        itemStates:
          type: array
          description: Aggregated order item states
          example:
            - new
            - canceled
            - waiting for documents
          items:
            type: string
            description: State which belongs to at least one order item
            example: new
        itemCount:
          type: integer
          description: Count of unique order items
        shipments:
          type: array
          description: An order contains at least one shipment group
          items:
            $ref: '#/components/schemas/type_15'
        updatedAt:
          type: string
          description: Order update date and time in UTC
          example: 2024-04-01 23:59:59
        createdAt:
          type: string
          description: Order creation date and time in UTC
          example: 2024-04-01 23:59:59
    type_10:
      required:
        - address1
        - address2
        - address3
        - city
        - company
        - country
        - firstName
        - lastName
        - phone
        - salutation
        - zipCode
      type: object
      properties:
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        company:
          type: string
        address1:
          type: string
          description: Street name
        address2:
          type: string
          description: House number
        address3:
          type: string
          description: District or neighborhood
        zipCode:
          type: string
        city:
          type: string
        country:
          type: string
        phone:
          type: string
    type_11:
      required:
        - cnpj
        - companyName
        - customerReference
        - email
        - fullName
        - ie
      type: object
      properties:
        customerReference:
          type: string
          description: Unique identifier of the customer
          example: BR--2
        fullName:
          type: string
          description: Customer name including salutation
          example: Mr Max Mustermann
        email:
          type: string
          example: max@mustermann.com
        cnpj:
          type: string
          description: CNPJ (Cadastro Nacional da Pessoa Jurídica) of the workshop
          example: 12.345.678/0001-23
        ie:
          type: string
          description: IE (Inscrição Estadual) of the workshop
          example: 123.456.789.012
        companyName:
          type: string
          description: Customer's workshop name
          example: Caterham Performance
    type_12:
      required:
        - canceled
        - commission
        - discount
        - grand
        - orderExpense
        - refundable
        - subtotal
      type: object
      properties:
        subtotal:
          type: string
          description: Amount before discounts
          example: '299.95'
        orderExpense:
          type: string
          description: Amount of order expenses (shipping costs)
          example: '0.00'
        grand:
          type: string
          description: Amount that the customer needed to pay
          example: '249.95'
        canceled:
          type: string
          description: Amount of canceled items
          example: '0.00'
        refundable:
          type: string
          description: Refundable amount
          example: '249.95'
        commission:
          type: string
          description: Marketplace operator fee
          example: '24.99'
        discount:
          type: string
          description: Sum of discounts (such as vouchers or promotions)
          example: '50.00'
    type_13:
      required:
        - merchantOrderItemReference
        - notaFiscal
        - product
        - quantity
        - state
        - totals
        - trackingLink
      type: object
      properties:
        merchantOrderItemReference:
          type: string
          description: Unique identifier for order item
          example: 715fba0fdef4f68b6146524b44e8fac2
        state:
          type: string
          example: new
        product:
          $ref: '#/components/schemas/type_16'
        quantity:
          type: integer
          example: 1
        totals:
          required:
            - discountTotal
            - sumPrice
            - sumPriceToPay
            - unitPrice
          type: object
          properties:
            unitPrice:
              type: string
              example: '1.09'
            sumPrice:
              type: string
              example: '1.09'
            sumPriceToPay:
              type: string
              example: '1.09'
            discountTotal:
              type: string
              example: '1.09'
        notaFiscal:
          type: string
        trackingLink:
          type: string
    type_14:
      required:
        - address
        - carrierName
        - merchantOrderItemReferences
        - name
        - shipmentReference
      type: object
      properties:
        name:
          type: string
          description: Shipment method name
          example: Standard
        address:
          $ref: '#/components/schemas/type_10'
        carrierName:
          type: string
          description: Shipment carrier name
          example: Entrega
        merchantOrderItemReferences:
          type: array
          description: References of order items which belong to this shipment
          example:
            - 715fba0fdef4f68b6146524b44e8fac2
            - ff33f8f4f90f8efe400abeab49a76788
          items:
            type: string
            description: Unique identifier for order item
            example: 715fba0fdef4f68b6146524b44e8fac2
        shipmentReference:
          type: string
          description: Unique identifier for shipment group
          example: '50'
      description: Shipment which belongs to at least one order item
    type_15:
      required:
        - carrierName
        - name
        - shipmentReference
      type: object
      properties:
        shipmentReference:
          type: string
          description: Unique identifier for shipment group
          example: '50'
        name:
          type: string
          description: Shipment method name
          example: Standard
        carrierName:
          type: string
          description: Shipment carrier name
          example: Entrega
      description: Shipment which belongs to at least one order item
    type_16:
      required:
        - brand
        - name
        - partNumber
        - sku
      type: object
      properties:
        sku:
          type: string
          example: continental__7pk1525rnh
        name:
          type: string
          example: CORREIA DE ACESSÓRIOS POLY V 1525MM CONTINENTAL - 7PK1525RNH
        brand:
          type: string
          example: CONTINENTAL
        partNumber:
          type: string
          example: 7PK1525RNH
    type_17:
      required:
        - data
      type: object
      properties:
        data:
          required:
            - merchantOrderItemReferences
          type: object
          properties:
            merchantOrderItemReferences:
              type: array
              description: List of unique identifiers of order items
              example:
                - 715fba0fdef4f68b6146524b44e8fac2
                - ff33f8f4f90f8efe400abeab49a76788
              items:
                type: string
                description: Unique identifier for order item
                example: 715fba0fdef4f68b6146524b44e8fac2
            merchantInternalOrderReference:
              type: string
              description: Unique identifier for order item on seller's system
              example: seller_1234
    type_18:
      type: array
      example:
        data:
          - productOfferReference: offer_MER000002-bosch__0-261-500-109
            merchantSku: MER000002
            brand: BOSCH
            partNumber: 0 261 500 109
            quantity: '50'
            isNeverOutOfStock: false
            isActive: true
            netPrice: '1000.00'
        errors:
          - code: 4003
            status: 400
            message: Falha na validação
            details:
              - message: Nenhum produto encontrado para a marca BOSCH e partNumber 0 280
                  157 501
                parameters: []
                entityIdentifier: '1'
      items:
        $ref: '#/components/schemas/type_1'
x-original-swagger-version: '2.0'
